name = "luxe-hotel"
type = "javascript"
main = "src/index.ts"
compatibility_date = "2024-12-06"

[env.production]
vars = { ENVIRONMENT = "production" }

[env.preview]
vars = { ENVIRONMENT = "preview" }

[env.development]
vars = { ENVIRONMENT = "development" }

# Pages configuration
pages_build_output_dir = "dist"
