pages_build_output_dir = "dist"
name = "luxe-hotel"
compatibility_date = "2024-12-06"

[build]
command = "npm run build"
cwd = ""
watch_paths = ["src/**/*.tsx", "src/**/*.ts", "src/**/*.css"]

[env.production]
name = "luxe-hotel-production"

[env.preview]
name = "luxe-hotel-preview"
