pages_build_output_dir = "dist"
name = "luxe-hotel"
compatibility_date = "2024-12-06"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "luxe-hotel"
database_id = "8322ba8b-4563-449a-8929-5b090ee6215f"
